### PR TITLE
Add contructor explicitly to AtomicQueueB2 Rollback

### LINKED ISSUE #109: v1.9.3 breaks AtomicQueueB2
Hi!

With 1.9.3 I get the following build error:

```
/opt/homebrew/Cellar/atomic_queue/1.9.3/include/atomic_queue/atomic_queue.h:785:18: error: no matching constructor for initialization of 'Rollback'
  785 |         Rollback rollback{this, 0}; // Strong exception safety: destroy and deallocate on exception.
      |                  ^       ~~~~~~~~~
../cxx/constellation/satellite/TransmitterSatellite.cpp:56:7: note: in instantiation of member function 'atomic_queue::AtomicQueueB2<constellation::message::CDTP2Message::DataRecord, std::allocator<constellation::message::CDTP2Message::DataRecord>, true, true>::AtomicQueueB2' requested here
   56 |       data_record_queue_(data_queue_size_) {
      |       ^
/opt/homebrew/Cellar/atomic_queue/1.9.3/include/atomic_queue/atomic_queue.h:759:9: note: candidate constructor not viable: requires 1 argument, but 2 were provided
  759 |         Rollback(Rollback const&) = delete;
      |         ^        ~~~~~~~~~~~~~~~
1 error generated.
```

I think this is caused by 957f45765e98ddc918787745bbd15a302af3d091 but I haven't managed to fully figure out why this happens yet.

### PR DESCRIPTION
**Pull request by stephanlachnit**
Closes https://github.com/max0x7ba/atomic_queue/issues/109

Not entirely sure what you prefer as code style for the arguments since it's a struct.

### CODE REVIEW

File: include/atomic_queue/atomic_queue.h [hunk 1]
```diff
@@ -756,6 +756,7 @@ class AtomicQueueB2 : private std::allocator_traits<A>::template rebind_alloc<un
         AtomicQueueB2* that;
         unsigned n_constructed;
 
+        Rollback(AtomicQueueB2* _that, unsigned _n_constructed) : that(_that), n_constructed(_n_constructed) {}
```
Comment (max0x7ba) [inline include/atomic_queue/atomic_queue.h]:
```
ATOMIC_QUEUE_INLINE Rollback(AtomicQueueB2* that) noexcept 
   : that(that)
   , n_constructed() 
{}
```

This would be ideal, please. 

No need for `n_constructed` argument if this constructor has to be defined.

**Review by max0x7ba — CHANGES_REQUESTED** [review]

**Comment by max0x7ba** [comment]
Thank you for your fix, Stephan!
