### ISSUE TITLE
v1.9.3 breaks AtomicQueueB2

### ISSUE THREAD

**Issue by stephanlachnit** [max0x7ba/atomic_queue#109]
Hi!

With 1.9.3 I get the following build error:

```
/opt/homebrew/Cellar/atomic_queue/1.9.3/include/atomic_queue/atomic_queue.h:785:18: error: no matching constructor for initialization of 'Rollback'
  785 |         Rollback rollback{this, 0}; // Strong exception safety: destroy and deallocate on exception.
      |                  ^       ~~~~~~~~~
../cxx/constellation/satellite/TransmitterSatellite.cpp:56:7: note: in instantiation of member function 'atomic_queue::AtomicQueueB2<constellation::message::CDTP2Message::DataRecord, std::allocator<constellation::message::CDTP2Message::DataRecord>, true, true>::AtomicQueueB2' requested here
   56 |       data_record_queue_(data_queue_size_) {
      |       ^
/opt/homebrew/Cellar/atomic_queue/1.9.3/include/atomic_queue/atomic_queue.h:759:9: note: candidate constructor not viable: requires 1 argument, but 2 were provided
  759 |         Rollback(Rollback const&) = delete;
      |         ^        ~~~~~~~~~~~~~~~
1 error generated.
```

I think this is caused by 957f45765e98ddc918787745bbd15a302af3d091 but I haven't managed to fully figure out why this happens yet.

**Comment by stephanlachnit** [comment]
Ok so I simply added this line:

```c++
Rollback(AtomicQueueB2* that_, unsigned n_constructed_) : that(that_), n_constructed(n_constructed_) {}
```

which fixed the compilation. Might be a weird Apple clang issue.

**Comment by max0x7ba** [comment]
> Might be a weird Apple clang issue.

What are the compiler command line options to reproduce this error, please?

**Comment by max0x7ba** [comment]
> > Might be a weird Apple clang issue.
> 
> What are the compiler command line options to reproduce this error, please?

Ah, compiling with `-std=c++20` causes this error.
